"""Puertos de persistencia. Un repositorio por raíz de agregado."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from factory.domain.entities import (
    Build,
    Conversation,
    Deployment,
    ModuleInstallation,
    Organization,
    Project,
    Specification,
    User,
)
from factory.domain.entities.specification import RequirementsDocument


@runtime_checkable
class OrganizationRepository(Protocol):
    async def add(self, organization: Organization) -> None: ...
    async def get(self, organization_id: str) -> Organization | None: ...
    async def get_by_slug(self, slug: str) -> Organization | None: ...


@runtime_checkable
class UserRepository(Protocol):
    async def add(self, user: User) -> None: ...
    async def get(self, user_id: str) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def list_for_organization(self, organization_id: str) -> list[User]: ...


@runtime_checkable
class ProjectRepository(Protocol):
    async def add(self, project: Project) -> None: ...
    async def get(self, project_id: str) -> Project | None: ...
    async def update(self, project: Project) -> None: ...
    async def delete(self, project_id: str) -> None: ...
    async def list_for_organization(
        self, organization_id: str, *, limit: int = 50, offset: int = 0
    ) -> list[Project]: ...
    async def count_for_organization(self, organization_id: str) -> int: ...


@runtime_checkable
class ConversationRepository(Protocol):
    async def add(self, conversation: Conversation) -> None: ...
    async def get(self, conversation_id: str) -> Conversation | None: ...
    async def get_for_project(self, project_id: str) -> Conversation | None: ...
    async def update(self, conversation: Conversation) -> None: ...


@runtime_checkable
class SpecificationRepository(Protocol):
    async def add_requirements(self, requirements: RequirementsDocument) -> None: ...
    async def get_requirements(self, requirements_id: str) -> RequirementsDocument | None: ...
    async def latest_requirements(self, project_id: str) -> RequirementsDocument | None: ...
    async def add(self, specification: Specification) -> None: ...
    async def get(self, specification_id: str) -> Specification | None: ...
    async def latest_for_project(self, project_id: str) -> Specification | None: ...


@runtime_checkable
class BuildRepository(Protocol):
    async def add(self, build: Build) -> None: ...
    async def get(self, build_id: str) -> Build | None: ...
    async def update(self, build: Build) -> None: ...
    async def list_for_project(self, project_id: str, *, limit: int = 20) -> list[Build]: ...
    async def latest_for_project(self, project_id: str) -> Build | None: ...


@runtime_checkable
class DeploymentRepository(Protocol):
    async def add(self, deployment: Deployment) -> None: ...
    async def get(self, deployment_id: str) -> Deployment | None: ...
    async def update(self, deployment: Deployment) -> None: ...
    async def list_for_project(self, project_id: str, *, limit: int = 20) -> list[Deployment]: ...
    async def active_for_project(self, project_id: str) -> Deployment | None: ...


@runtime_checkable
class ModuleRepository(Protocol):
    async def add(self, installation: ModuleInstallation) -> None: ...
    async def update(self, installation: ModuleInstallation) -> None: ...
    async def get(self, project_id: str, module_key: str) -> ModuleInstallation | None: ...
    async def list_for_project(self, project_id: str) -> list[ModuleInstallation]: ...
    async def remove(self, project_id: str, module_key: str) -> None: ...
